affinity: {}
config:
  DEVICE_STATUS_UPDATE_PERIOD_MINS: 5
  DEVICE_UPDATE_PERIOD_HRS: 4
  api_root: null
  log_verbosity: WARN
  mqttbroker_url: ""
  project: MERCK_PHARMA
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: local-docker-registry:5001/discovery
imagePullSecrets: []
nameOverride: ""
nodeSelector: {}
podSecurityContext: {}
replicaCount: 1
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 4000m
    memory: 8Gi
securityContext: {}
serviceAccount:
  create: true
  name: null
tolerations: []
