apiVersion: v2
appVersion: v1.11.0
description: Kafka Connect Cluster & Phizzle Connectors Helm chart for Kubernetes
home: https://phizzle.com
maintainers:
- email: phizzle@phizzle.com
  name: Phizzle
  
name: kafkaconnect
type: application
version: 1.11.0
