actionManagerAPIURL: ""
affinity: {}
config:
  ALLOW_DEFAULT_SITE_ONLY: "true"
  AUTO_SCHEDULED_DUE_DATE_FOR: "0"
  CP_MAX_SIZE: "3"
  CP_MIN_SIZE: "1"
  app_host: 0.0.0.0
  app_port: "9001"
  by_pass_authentication: "false"
  expiry_limit: NA
  log_level: WARN
  pharma_api_access_key: PHASOAPX355K3Y
  pharma_api_private_key: pharma50A9
  pharma_api_secret_key: SOAP5E637
database:
  database: merck
  host: ""
  password: tea
  port: "5432"
  username: postgres
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: local-docker-registry:5001/soap-connector
imagePullSecrets: []
nameOverride: ""
nodeSelector: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 80
  type: LoadBalancer
serviceAccount:
  create: true
  name: null
tolerations: []
