apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafkacluster.fullname" . }}-jmx-certs
  labels:
    {{- include "kafkacluster.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.jmxCertificates .Values.jmxCertificates.keystorePath }}
  keystore.jks: {{ .Files.Get .Values.jmxCertificates.keystorePath | b64enc }}
  truststore.jks: {{ .Files.Get .Values.jmxCertificates.truststorePath | b64enc }}
  {{- else }}
  # Run scripts/generate-jmx-certificates.sh to create certificates
  keystore.jks: ""
  truststore.jks: ""
  {{- end }}