apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafkacluster.fullname" . }}-jmx-certs
  labels:
    {{- include "kafkacluster.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.jmxCertificates }}
  jmx-keystore.jks: {{ .Values.jmxCertificates.keystore | b64enc }}
  jmx-truststore.jks: {{ .Values.jmxCertificates.truststore | b64enc }}
  {{- end }}