apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafkacluster.fullname" . }}-jmx-certs
  labels:
    {{- include "kafkacluster.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.jmxCertificates .Values.jmxCertificates.keystore }}
  keystore.jks: {{ .Values.jmxCertificates.keystore }}
  truststore.jks: {{ .Values.jmxCertificates.truststore }}
  {{- else }}
  # Placeholder - Replace with actual base64 encoded certificates
  keystore.jks: ""
  truststore.jks: ""
  {{- end }}