apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics
  labels:
    {{- include "kafkacluster.labels" . | nindent 4 }}
data:
  kafka-metrics-config.yml: |
    # Secure JMX metrics configuration for Prometheus
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    
    # Whitelist of metrics to expose
    whitelistObjectNames:
      - kafka.server:type=BrokerTopicMetrics,name=*
      - kafka.server:type=ReplicaManager,name=*
      - kafka.controller:type=KafkaController,name=*
      - kafka.network:type=RequestMetrics,name=*,request=*
      - kafka.server:type=KafkaRequestHandlerPool,name=*
      - kafka.server:type=KafkaServer,name=*
      - kafka.server:type=ReplicaFetcherManager,name=*
      - kafka.log:type=LogManager,name=*
      - kafka.cluster:type=Partition,name=*,topic=*,partition=*
      - kafka.consumer:type=consumer-fetch-manager-metrics,client-id=*
      - kafka.producer:type=producer-metrics,client-id=*
      
    rules:
      # Broker Topic Metrics
      - pattern: kafka.server<type=BrokerTopicMetrics, name=(.+), topic=(.+)><>Count
        name: kafka_server_brokertopicmetrics_$1_total
        type: COUNTER
        labels:
          topic: "$2"
          
      - pattern: kafka.server<type=BrokerTopicMetrics, name=(.+)><>Count
        name: kafka_server_brokertopicmetrics_$1_total
        type: COUNTER
        
      # Request Metrics
      - pattern: kafka.network<type=RequestMetrics, name=RequestsPerSec, request=(.+)><>Count
        name: kafka_network_requestmetrics_requests_total
        type: COUNTER
        labels:
          request: "$1"
          
      # Controller Metrics
      - pattern: kafka.controller<type=KafkaController, name=(.+)><>Value
        name: kafka_controller_$1
        type: GAUGE
        
      # Replica Manager Metrics
      - pattern: kafka.server<type=ReplicaManager, name=(.+)><>Value
        name: kafka_server_replicamanager_$1
        type: GAUGE
        
      # Generic JMX metrics
      - pattern: ".*"