apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "kafkacluster.fullname" . }}
spec:
  kafka:
    {{- if .Values.kafka.replicas }}
    replicas: {{ .Values.kafka.replicas }}
    {{- end }}
    {{- if .Values.kafka.version }}
    version: {{ .Values.kafka.version }}
    {{- end }}
    {{- if .Values.kafka.config }}
    config:
      {{- toYaml .Values.kafka.config | nindent 6 }}
    {{- end }}
    {{- if .Values.kafka.listeners }}
    listeners:
      {{- toYaml .Values.kafka.listeners | nindent 6 }}
    {{- end }}
    {{- if .Values.kafka.storage }}
    storage:
      {{- toYaml .Values.kafka.storage | nindent 6 }}
    {{- end }}
    {{- if .Values.kafka.jmxOptions }}
    jmxOptions:
      {{- toYaml .Values.kafka.jmxOptions | nindent 6 }}
    {{- end }}
    {{- if .Values.kafka.jvmOptions }}
    jvmOptions:
      {{- toYaml .Values.kafka.jvmOptions | nindent 6 }}
    {{- end }}
    {{- if .Values.kafka.metricsConfig }}
    metricsConfig:
      {{- toYaml .Values.kafka.metricsConfig | nindent 6 }}
    {{- end }}
    template:
      pod:
        volumes:
          {{- if and .Values.jmxCertificates .Values.jmxCertificates.keystore }}
          - name: jmx-certificates
            secret:
              secretName: {{ include "kafkacluster.fullname" . }}-jmx-certs
          {{- end }}
          - name: jmx-ssl-config
            configMap:
              name: {{ include "kafkacluster.fullname" . }}-jmx-ssl-config
      kafkaContainer:
        volumeMounts:
          {{- if and .Values.jmxCertificates .Values.jmxCertificates.keystore }}
          - name: jmx-certificates
            mountPath: /opt/kafka/certificates
            readOnly: true
          {{- end }}
          - name: jmx-ssl-config
            mountPath: /opt/kafka/jmx
            readOnly: true
        env:
          {{- if and .Values.jmxCertificates .Values.jmxCertificates.keystore }}
          - name: JMX_KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "kafkacluster.fullname" . }}-jmx-passwords
                key: JMX_KEYSTORE_PASSWORD
          - name: JMX_TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "kafkacluster.fullname" . }}-jmx-passwords
                key: JMX_TRUSTSTORE_PASSWORD
          {{- end }}
  zookeeper:
    {{- if .Values.zookeeper.replicas }}
    replicas: {{ .Values.zookeeper.replicas }}
    {{- end }}
    {{- if .Values.zookeeper.storage }}
    storage:
      {{- toYaml .Values.zookeeper.storage | nindent 6 }}
    {{- end }}
    {{- if .Values.zookeeper.jmxOptions }}
    jmxOptions:
      {{- toYaml .Values.zookeeper.jmxOptions | nindent 6 }}
    {{- end }}
    {{- if .Values.zookeeper.jvmOptions }}
    jvmOptions:
      {{- toYaml .Values.zookeeper.jvmOptions | nindent 6 }}
    {{- end }}
    template:
      pod:
        volumes:
          {{- if and .Values.jmxCertificates .Values.jmxCertificates.keystore }}
          - name: jmx-certificates
            secret:
              secretName: {{ include "kafkacluster.fullname" . }}-jmx-certs
          {{- end }}
          - name: jmx-ssl-config
            configMap:
              name: {{ include "kafkacluster.fullname" . }}-jmx-ssl-config
      zookeeperContainer:
        volumeMounts:
          {{- if and .Values.jmxCertificates .Values.jmxCertificates.keystore }}
          - name: jmx-certificates
            mountPath: /opt/kafka/certificates
            readOnly: true
          {{- end }}
          - name: jmx-ssl-config
            mountPath: /opt/kafka/jmx
            readOnly: true
        env:
          {{- if and .Values.jmxCertificates .Values.jmxCertificates.keystore }}
          - name: JMX_KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "kafkacluster.fullname" . }}-jmx-passwords
                key: JMX_KEYSTORE_PASSWORD
          - name: JMX_TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "kafkacluster.fullname" . }}-jmx-passwords
                key: JMX_TRUSTSTORE_PASSWORD
          {{- end }}
  {{- if .Values.entityOperator }}
  entityOperator:
    {{- toYaml .Values.entityOperator | nindent 4 }}
  {{- end }}