affinity: {}
annotations: {}
client: {}
config:
  auth_enabled: false
  chunk_store_config:
    max_look_back_period: 0s
  ingester:
    chunk_block_size: 262144
    chunk_idle_period: 3m
    chunk_retain_period: 1m
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
    max_transfer_retries: 0
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
  schema_config:
    configs:
    - from: "2018-04-15"
      index:
        period: 168h
        prefix: index_
      object_store: filesystem
      schema: v9
      store: boltdb
  server:
    http_listen_port: 3100
  storage_config:
    boltdb:
      directory: /data/loki/index
    filesystem:
      directory: /data/loki/chunks
  table_manager:
    retention_deletes_enabled: false
    retention_period: 0s
env: []
extraArgs: {}
extraContainers: []
extraPorts: []
extraVolumeMounts: []
extraVolumes: []
image:
  pullPolicy: IfNotPresent
  repository: grafana/loki
  tag: 1.5.0
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
initContainers: []
livenessProbe:
  httpGet:
    path: /ready
    port: http-metrics
  initialDelaySeconds: 45
networkPolicy:
  enabled: false
nodeSelector: {}
persistence:
  accessModes:
  - ReadWriteOnce
  annotations: {}
  enabled: false
  size: 10Gi
podAnnotations:
  prometheus.io/port: http-metrics
  prometheus.io/scrape: "true"
podDisruptionBudget: {}
podLabels: {}
podManagementPolicy: OrderedReady
rbac:
  create: true
  pspEnabled: true
readinessProbe:
  httpGet:
    path: /ready
    port: http-metrics
  initialDelaySeconds: 45
replicas: 1
resources: {}
securityContext:
  fsGroup: 10001
  runAsGroup: 10001
  runAsNonRoot: true
  runAsUser: 10001
service:
  annotations: {}
  labels: {}
  nodePort: null
  port: 3100
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: null
serviceMonitor:
  additionalLabels: {}
  annotations: {}
  enabled: false
  interval: ""
terminationGracePeriodSeconds: 4800
tolerations: []
tracing:
  jaegerAgentHost: null
updateStrategy:
  type: RollingUpdate
