apiVersion: v1
appVersion: v1.5.0
dependencies:
- condition: loki.enabled
  name: loki
  repository: file://../loki
  version: ^0.6.0
- condition: promtail.enabled
  name: promtail
  repository: file://../promtail
  version: ^0.6.0
- condition: fluent-bit.enabled
  name: fluent-bit
  repository: file://../fluent-bit
  version: ^0.0.1
- condition: grafana.enabled
  name: grafana
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: ~3.8.15
- condition: prometheus.enabled
  name: prometheus
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: ~9.3.0
description: 'Loki: like Prometheus, but for logs.'
home: https://grafana.com/loki
icon: https://github.com/grafana/loki/raw/master/docs/logo.png
kubeVersion: ^1.10.0-0
maintainers:
- email: lokiproject@googlegroups.com
  name: Loki Maintainers
name: loki-stack
sources:
- https://github.com/grafana/loki
version: 0.38.1
