entityOperator:
  topicOperator: {}
  userOperator: {}
kafka:
  config:
    auto.create.topics.enable: false
    log.message.format.version: "2.8"
    offsets.topic.replication.factor: 3
    transaction.state.log.min.isr: 2
    transaction.state.log.replication.factor: 3
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    # plain: {}
    # tls: {}
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
  version: 3.9.0
  # JMX configuration - using password auth with Strimzi
  jmxOptions:
    authentication:
      type: password
  jvmOptions:
    "-Xmx": "2G"
    "-Xms": "2G"
    "-XX":
      "UseG1GC": "true"
      "MaxGCPauseMillis": "20"
    javaSystemProperties:
      # Enable SSL for JMX
      - name: "com.sun.management.jmxremote.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.registry.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.ssl.need.client.auth"
        value: "true"
      # SSL keystore and truststore using mounted certificates
      - name: "javax.net.ssl.keyStore"
        value: "/mnt/jmx-certs/keystore.jks"
      - name: "javax.net.ssl.keyStorePassword"
        value: "${JMX_KEYSTORE_PASSWORD}"
      - name: "javax.net.ssl.trustStore"
        value: "/mnt/jmx-certs/truststore.jks"
      - name: "javax.net.ssl.trustStorePassword"
        value: "${JMX_TRUSTSTORE_PASSWORD}"
  # Metrics configuration for Prometheus JMX Exporter
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: kafka-metrics
        key: kafka-metrics-config.yml
strimzi-kafka-operator:
  watchAnyNamespace: true
zookeeper:
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
  # JMX configuration - using password auth with Strimzi
  jmxOptions:
    authentication:
      type: password
  jvmOptions:
    "-Xmx": "1G"
    "-Xms": "1G"
    "-XX":
      "UseG1GC": "true"
    javaSystemProperties:
      # Enable SSL for JMX
      - name: "com.sun.management.jmxremote.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.registry.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.ssl.need.client.auth"
        value: "true"
      # SSL keystore and truststore using mounted certificates
      - name: "javax.net.ssl.keyStore"
        value: "/mnt/jmx-certs/keystore.jks"
      - name: "javax.net.ssl.keyStorePassword"
        value: "${JMX_KEYSTORE_PASSWORD}"
      - name: "javax.net.ssl.trustStore"
        value: "/mnt/jmx-certs/truststore.jks"
      - name: "javax.net.ssl.trustStorePassword"
        value: "${JMX_TRUSTSTORE_PASSWORD}"

# JMX SSL Certificates
# Generate these using scripts/generate-jmx-certificates.sh
jmxCertificates:
  # Base64 encoded keystore file
  keystore: "/u3+7QAAAAIAAAACAAAAAgAGY2Fyb290AAABmHT8EDoABVguNTA5AAADmTCCA5UwggJ9oAMCAQICCQCiw9aPYWAmXTANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJVUzEOMAwGA1UECAwFU3RhdGUxDTALBgNVBAcMBENpdHkxFTATBgNVBAoMDE9yZ2FuaXphdGlvbjELMAkGA1UECwwCSVQxDzANBgNVBAMMBkpNWC1DQTAeFw0yNTA4MDQxMjA4NTJaFw0zNTA4MDIxMjA4NTJaMGExCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMQswCQYDVQQLDAJJVDEPMA0GA1UEAwwGSk1YLUNBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwF6/iYrMs2oMFzPoUa2jiYIQD1hRLfECG87rNsSBZy5aVebIp4Asz5sJFqjP5H1aKMnzmBr1UudZZ5aKQvpCJao8s8aqTjQyhM66fyI/cyf3JdelbIrPOs0Ue2UQ5QvyAbPCQXhdY2BMkQz7hmTS+qIm5hcA8qeWfJ/jSBd+DQao6bZnogI2YzNsyMSwJDVPsu0dgljdVME7dL6FYOkQE1kWwRKznBXlAyMT1BEXaqbD9axU/tzEgtby81GKVwFvlqCiM3NxbBaNv9M7+TiELmXNJceOUioeknXzwBGPQyxR7hVTi4SZXvrGnfZdal25GYttuOliaTJ1PP44rY8U9wIDAQABo1AwTjAdBgNVHQ4EFgQUZhL9ycThdtRgqH73r9xRy76BkG0wHwYDVR0jBBgwFoAUZhL9ycThdtRgqH73r9xRy76BkG0wDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAPyUc2ZpWfKW4OJ4n9Tlr1wo59rNos5lBaOtzHlKPD4ufqZf+M68AW8AcY9axMEihxCPA4LG2ypyFuzaiSAoOo47RJTqLj7C6zII0LdjyVfZ/aTX46q8XFI+O8zQRCfooLO55DWVbRJu782ismbnGrvLizGYuVyB6iZVhxctGKDyqo9qLnW16CzhoE3xH0fhyRaJHBKpPec3MQVumUdnYvACcPZ0jdR3R3xfNDhHkAX4pX2OpOVLYAgkxcRMA0JJ0/ymHKWziKUMc+STcJ9W3HumC0eo0I/axni/J9m3WerkcNywDZda9cTLzkJ9HiOQ1xE2jnOnTkJKBDKqCWcfa2gAAAAEACWthZmthLWpteAAAAZh0/BD4AAAFAjCCBP4wDgYKKwYBBAEqAhEBAQUABIIE6nFuwarlV6S/4+SKdRd6bzcrf7byuhK6VAtsRzc/YFycUEdB5zTeXtPnvcpg5VCWK1DBy+1cIufLnqTeg2SrG9/KCPF3WnQ26E4wvFd54kI8v6bSZ/ESi8wnkOWh850MKG1J62tUdxt4yMcQEoGjNLmmb5Ztsph6/BNEUy85WIlQ6OjZHSRW3lbhzNJWJFl3lGT5RURohrH7+Ts3RRZCn1LmG+gSQbwW29EpFkCdq7iWJIrkytAayYfJ2MxpOgBg04vqqOY1vkSMoeVHAZstGWtH9NW6Kb5g7mlYDUVZkt7VAE3mKRGQECHiYJsKVf/mOZdKOezjhzZPs7SekaqQcJMCGEypfpH6l6g8LH4Et8jwV1jOhKyO7ciSNPTcIsTmeO7kk906Nx8Vhn4w353qcTc5Nq78zHDBaovX1BNZCAUNxWP69Dh+BprB4KxSpPTYvjIrpOqeP0BNqYS9zTyK00YDZz5G4ZiqgLGTzifWfMKMs7BWX/ihRKdDt3fV6Io1DLrwmb5kkckf2HkSZcoMMI35uyw3JYl7enCz9mebPwoSweUIVSNDACN4OLj5m7Q9wIqW6A+LOCzrb5oJ76Fv5fCW7I61Mngj95u7sd4mGLgRp3pV4Wy87wMXPmUibvprFecC3sOZNAWwirH74hbNwh7/gsSTiRc11b+8OFn6Nppei4ZsH1MFJvdzANG3/wniXSs44HyyRBPbPO37F97wmzkT5R54sRAqh+Tn5O61x5HwuE5l35pLSOkZNdiZEj8RVLtB9Bc6kAXV3A9Hrl8h0gfQek0pzxLj64tKoTkedklK5MiDxjwWDeP84ZCS6+M32uA4PnlNjBPeR0SDQB2MLV/sOq/jXNT8liePQR9VR9FKEdeNHgFb0Ia5IVt5auQDmnGOo5K3sehl3Fib+2g/9uXpRrxEBf3zgNdc2ZNvys3fsTFUxYxgTRu2Ec/2rr2tjlShr7VYn77h1uZ3bXb90JtXo3l+/jf3GoToRoruBFHpfd4hwcvnRoLmyuXOx0tbSTvMiBWWEKcy0vEOIPvNwS4XPmKLObvjlxENTF8T88GppkVqP2TbYxxG2/TPjReX/flERRT2sxsjA17g4H8tN7cYTWl0qfalezPmcHhlanILiXqSGTpXxZS8IzVJR6AhBKyq95Cv97a39YOP8zYn7YQ1xMoNewhMMJ21qQkadE+/nMjxkuxEMAvqa83K7xAUbP4dsfp4PbQRtjSGdM6FO6e4nYtie4pwg0RaOHHAcM00Pq62iisjJe7iKgxHk8i4UXdhnUeE7917jLoxgn4OkXcUUTLa4wn/Ck9d+5XN9ukZH5iNlJt1/Cikrxrc1Vl2sj9qlPle3Ie9Fr3AkfTxt+h4P2dIMxTdWi6QcNS+E+r9sy1+uwFFXMkjz2wB1OvV/M0viNg5iXFz5oB/SdpJ8my+woah9kD0SMDI9yHrOoGbG9H3zIVvLHjTl308RANLASzWQt9UWnic2txrWllSIX5+cmli1bXPSpaxtgOg58F7QfdCA4+i/NLaoErSvLvCGmc71OyX4EEIqUZZ+qLjEhvU4JwTwIgFfw5SJNusy2tsWbPna2KrSuyUntO9Am4fmONb28KI97Xm1couCANTwx/Yw3w/pbIF3egF9FlclqU1JnEmWtdedKG9VVyxWik/CWcMQviKGxAz+5MAAAACAAVYLjUwOQAAA0UwggNBMIICKQIJAKQyO+7FLQ4cMA0GCSqGSIb3DQEBCwUAMGExCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMQswCQYDVQQLDAJJVDEPMA0GA1UEAwwGSk1YLUNBMB4XDTI1MDgwNDEyMDg1MloXDTM1MDgwMjEyMDg1MlowZDELMAkGA1UEBhMCVVMxDjAMBgNVBAgTBVN0YXRlMQ0wCwYDVQQHEwRDaXR5MRUwEwYDVQQKEwxPcmdhbml6YXRpb24xCzAJBgNVBAsTAklUMRIwEAYDVQQDEwlrYWZrYS1qbXgwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCuwV17Zv1OTKmk2UqXQCRzgvGHjwqy3pF20XCV0IG92RBjo44UTRy4y3jWpe+V4X3NLz4FyKHlkdDNfT9q9ekyjKaVDAgyJ787iR/b5mnN4wCBnnY7v0/ik+mEn9jDibwZa9EW2M6lnBzH9rOsEXXtLIy/eMXFgL52tsF/86079+EyOms/5m36gx0qeQ0CdUw40AOOv5mBAC7d7ztpC3Z1z7XJfOqHtFj+TBZY6sHU6AJuV3/+ABubdWC/EfO/N1zLr9FFqTq0JL6KkpdI+HYiH46Ha7ntuQ61gy/ez8PXCyODIvYt+yyWzMNXOQ00cXXvv+qlOxitcV9sd4rtqUDfAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAB3IlafjWpP6Uhs7Wi3TJ0K4Gk8MERgGKRiK5pPmm9zmGwXiMcX+xOtsqxoLbNoF4QJG0GtPRiVRW7YnYftOqmFLZwJlV9rpi6xPTNgGVje/8HzbhayuvYwYwHHbyf+vtuw8WzngrNCQvxZ9M74dv+xEZC4AiQX/oCrbQxTWznHMcXaZoo373+isEjxfiSOVf0UjDNoGXGtpthHKtmVcQH8lIjN2Zn+3Xn9F/vLVqxLsXovBbAGvxlI+qsmKbV6mmUmLE04AWO4OliNctifYRTNfkmwjEe9KpmS8yFPuKQJpLUjSlHVLPaEuScmi2XI9GztSo9xm/h2NbeO/VqhxgT8ABVguNTA5AAADmTCCA5UwggJ9oAMCAQICCQCiw9aPYWAmXTANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJVUzEOMAwGA1UECAwFU3RhdGUxDTALBgNVBAcMBENpdHkxFTATBgNVBAoMDE9yZ2FuaXphdGlvbjELMAkGA1UECwwCSVQxDzANBgNVBAMMBkpNWC1DQTAeFw0yNTA4MDQxMjA4NTJaFw0zNTA4MDIxMjA4NTJaMGExCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMQswCQYDVQQLDAJJVDEPMA0GA1UEAwwGSk1YLUNBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwF6/iYrMs2oMFzPoUa2jiYIQD1hRLfECG87rNsSBZy5aVebIp4Asz5sJFqjP5H1aKMnzmBr1UudZZ5aKQvpCJao8s8aqTjQyhM66fyI/cyf3JdelbIrPOs0Ue2UQ5QvyAbPCQXhdY2BMkQz7hmTS+qIm5hcA8qeWfJ/jSBd+DQao6bZnogI2YzNsyMSwJDVPsu0dgljdVME7dL6FYOkQE1kWwRKznBXlAyMT1BEXaqbD9axU/tzEgtby81GKVwFvlqCiM3NxbBaNv9M7+TiELmXNJceOUioeknXzwBGPQyxR7hVTi4SZXvrGnfZdal25GYttuOliaTJ1PP44rY8U9wIDAQABo1AwTjAdBgNVHQ4EFgQUZhL9ycThdtRgqH73r9xRy76BkG0wHwYDVR0jBBgwFoAUZhL9ycThdtRgqH73r9xRy76BkG0wDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAPyUc2ZpWfKW4OJ4n9Tlr1wo59rNos5lBaOtzHlKPD4ufqZf+M68AW8AcY9axMEihxCPA4LG2ypyFuzaiSAoOo47RJTqLj7C6zII0LdjyVfZ/aTX46q8XFI+O8zQRCfooLO55DWVbRJu782ismbnGrvLizGYuVyB6iZVhxctGKDyqo9qLnW16CzhoE3xH0fhyRaJHBKpPec3MQVumUdnYvACcPZ0jdR3R3xfNDhHkAX4pX2OpOVLYAgkxcRMA0JJ0/ymHKWziKUMc+STcJ9W3HumC0eo0I/axni/J9m3WerkcNywDZda9cTLzkJ9HiOQ1xE2jnOnTkJKBDKqCWcfa2sB5ntO09CSXvs90b4bG5lm/YSJL"
  # Base64 encoded truststore file  
  truststore: "/u3+7QAAAAIAAAABAAAAAgAGY2Fyb290AAABmHT8EZwABVguNTA5AAADmTCCA5UwggJ9oAMCAQICCQCiw9aPYWAmXTANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJVUzEOMAwGA1UECAwFU3RhdGUxDTALBgNVBAcMBENpdHkxFTATBgNVBAoMDE9yZ2FuaXphdGlvbjELMAkGA1UECwwCSVQxDzANBgNVBAMMBkpNWC1DQTAeFw0yNTA4MDQxMjA4NTJaFw0zNTA4MDIxMjA4NTJaMGExCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMQswCQYDVQQLDAJJVDEPMA0GA1UEAwwGSk1YLUNBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwF6/iYrMs2oMFzPoUa2jiYIQD1hRLfECG87rNsSBZy5aVebIp4Asz5sJFqjP5H1aKMnzmBr1UudZZ5aKQvpCJao8s8aqTjQyhM66fyI/cyf3JdelbIrPOs0Ue2UQ5QvyAbPCQXhdY2BMkQz7hmTS+qIm5hcA8qeWfJ/jSBd+DQao6bZnogI2YzNsyMSwJDVPsu0dgljdVME7dL6FYOkQE1kWwRKznBXlAyMT1BEXaqbD9axU/tzEgtby81GKVwFvlqCiM3NxbBaNv9M7+TiELmXNJceOUioeknXzwBGPQyxR7hVTi4SZXvrGnfZdal25GYttuOliaTJ1PP44rY8U9wIDAQABo1AwTjAdBgNVHQ4EFgQUZhL9ycThdtRgqH73r9xRy76BkG0wHwYDVR0jBBgwFoAUZhL9ycThdtRgqH73r9xRy76BkG0wDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAPyUc2ZpWfKW4OJ4n9Tlr1wo59rNos5lBaOtzHlKPD4ufqZf+M68AW8AcY9axMEihxCPA4LG2ypyFuzaiSAoOo47RJTqLj7C6zII0LdjyVfZ/aTX46q8XFI+O8zQRCfooLO55DWVbRJu782ismbnGrvLizGYuVyB6iZVhxctGKDyqo9qLnW16CzhoE3xH0fhyRaJHBKpPec3MQVumUdnYvACcPZ0jdR3R3xfNDhHkAX4pX2OpOVLYAgkxcRMA0JJ0/ymHKWziKUMc+STcJ9W3HumC0eo0I/axni/J9m3WerkcNywDZda9cTLzkJ9HiOQ1xE2jnOnTkJKBDKqCWcfa2hYUwiopxpAsqyWfc0lJuPXmenhF"

# JMX Passwords
jmxPasswords:
  keystorePassword: "changeme"  # Replace with actual password used during certificate generation
  truststorePassword: "changeme"  # Replace with actual password used during certificate generation  
  # JMX authentication passwords
  monitorPassword: ""
  controlPassword: ""
