entityOperator:
  topicOperator: {}
  userOperator: {}
kafka:
  config:
    auto.create.topics.enable: false
    log.message.format.version: "2.8"
    offsets.topic.replication.factor: 3
    transaction.state.log.min.isr: 2
    transaction.state.log.replication.factor: 3
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    # plain: {}
    # tls: {}
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
  version: 3.9.0
strimzi-kafka-operator:
  watchAnyNamespace: true
zookeeper:
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
