entityOperator:
  topicOperator: {}
  userOperator: {}
kafka:
  config:
    auto.create.topics.enable: false
    log.message.format.version: "2.8"
    offsets.topic.replication.factor: 3
    transaction.state.log.min.isr: 2
    transaction.state.log.replication.factor: 3
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    # plain: {}
    # tls: {}
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
  version: 3.9.0
  # JMX configuration with SSL
  jmxOptions:
    authentication:
      type: password
  jvmOptions:
    "-Xmx": "2G"
    "-Xms": "2G"
    javaSystemProperties:
      - name: "com.sun.management.jmxremote"
        value: "true"
      - name: "com.sun.management.jmxremote.port"
        value: "9999"
      - name: "com.sun.management.jmxremote.rmi.port"
        value: "9999"
      - name: "com.sun.management.jmxremote.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.registry.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.ssl.need.client.auth"
        value: "true"
      - name: "javax.net.ssl.keyStore"
        value: "/opt/kafka/certificates/jmx-keystore.jks"
      - name: "javax.net.ssl.keyStorePassword"
        value: "${JMX_KEYSTORE_PASSWORD}"
      - name: "javax.net.ssl.trustStore"
        value: "/opt/kafka/certificates/jmx-truststore.jks"
      - name: "javax.net.ssl.trustStorePassword"
        value: "${JMX_TRUSTSTORE_PASSWORD}"
  # Metrics configuration for Prometheus JMX Exporter
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: kafka-metrics
        key: kafka-metrics-config.yml
strimzi-kafka-operator:
  watchAnyNamespace: true
zookeeper:
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
  # JMX configuration with SSL for Zookeeper
  jmxOptions:
    authentication:
      type: password
  jvmOptions:
    "-Xmx": "1G"
    "-Xms": "1G"
    javaSystemProperties:
      - name: "com.sun.management.jmxremote"
        value: "true"
      - name: "com.sun.management.jmxremote.port"
        value: "9998"
      - name: "com.sun.management.jmxremote.rmi.port"
        value: "9998"
      - name: "com.sun.management.jmxremote.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.registry.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.ssl.need.client.auth"
        value: "true"
      - name: "javax.net.ssl.keyStore"
        value: "/opt/kafka/certificates/jmx-keystore.jks"
      - name: "javax.net.ssl.keyStorePassword"
        value: "${JMX_KEYSTORE_PASSWORD}"
      - name: "javax.net.ssl.trustStore"
        value: "/opt/kafka/certificates/jmx-truststore.jks"
      - name: "javax.net.ssl.trustStorePassword"
        value: "${JMX_TRUSTSTORE_PASSWORD}"

# JMX SSL Certificates
# Generate these using scripts/generate-jmx-certificates.sh
jmxCertificates:
  # Base64 encoded keystore file
  keystore: ""
  # Base64 encoded truststore file  
  truststore: ""

# JMX Passwords
jmxPasswords:
  keystorePassword: ""
  truststorePassword: ""
