entityOperator:
  topicOperator: {}
  userOperator: {}
kafka:
  config:
    auto.create.topics.enable: false
    log.message.format.version: "2.8"
    offsets.topic.replication.factor: 3
    transaction.state.log.min.isr: 2
    transaction.state.log.replication.factor: 3
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    # plain: {}
    # tls: {}
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
  version: 3.9.0
  # JMX configuration - using password auth with Strimzi
  jmxOptions:
    authentication:
      type: password
  jvmOptions:
    "-Xmx": "2G"
    "-Xms": "2G"
    "-XX":
      "UseG1GC": "true"
      "MaxGCPauseMillis": "20"
    javaSystemProperties: []
  # Metrics configuration for Prometheus JMX Exporter
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: kafka-metrics
        key: kafka-metrics-config.yml
strimzi-kafka-operator:
  watchAnyNamespace: true
zookeeper:
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
  # JMX configuration - using password auth with Strimzi
  jmxOptions:
    authentication:
      type: password
  jvmOptions:
    "-Xmx": "1G"
    "-Xms": "1G"
    "-XX":
      "UseG1GC": "true"
    javaSystemProperties: []

# JMX SSL Certificates
# Generate these using scripts/generate-jmx-certificates.sh
jmxCertificates:
  keystorePath: "certs/keystore.jks"
  truststorePath: "certs/truststore.jks"

jmxPasswords:
  keystorePasswordPath: "certs/keystore.password"
  truststorePasswordPath: "certs/truststore.password"
  # JMX authentication passwords
  monitorPasswordPath: "certs/monitor.password"
  controlPasswordPath: "certs/control.password"

# JMX Exporter for secure JMX access (alternative to direct JMX SSL)
jmxExporter:
  enabled: false
  ssl:
    enabled: true
  username: ""
  password: ""

# JMX SSL Proxy - provides SSL wrapper for JMX without interfering with Strimzi
jmxSSLProxy:
  enabled: false  # Set to true to enable SSL for JMX
  image: alpine:3.19  # Image with stunnel and openssl
