entityOperator:
  topicOperator: {}
  userOperator: {}
kafka:
  config:
    auto.create.topics.enable: false
    log.message.format.version: "2.8"
    offsets.topic.replication.factor: 3
    transaction.state.log.min.isr: 2
    transaction.state.log.replication.factor: 3
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    # plain: {}
    # tls: {}
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
  version: 3.9.0
  # JMX configuration - using password auth with Strimzi
  jmxOptions:
    authentication:
      type: password
  jvmOptions:
    "-Xmx": "2G"
    "-Xms": "2G"
    "-XX":
      "UseG1GC": "true"
      "MaxGCPauseMillis": "20"
    javaSystemProperties:
      # Enable SSL for JMX
      - name: "com.sun.management.jmxremote.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.registry.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.ssl.need.client.auth"
        value: "true"
      # SSL keystore and truststore using mounted certificates
      - name: "javax.net.ssl.keyStore"
        value: "/mnt/jmx-certs/keystore.jks"
      - name: "javax.net.ssl.keyStorePassword"
        value: "${JMX_KEYSTORE_PASSWORD}"
      - name: "javax.net.ssl.trustStore"
        value: "/mnt/jmx-certs/truststore.jks"
      - name: "javax.net.ssl.trustStorePassword"
        value: "${JMX_TRUSTSTORE_PASSWORD}"
  # Metrics configuration for Prometheus JMX Exporter
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: kafka-metrics
        key: kafka-metrics-config.yml
strimzi-kafka-operator:
  watchAnyNamespace: true
zookeeper:
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
  # JMX configuration - using password auth with Strimzi
  jmxOptions:
    authentication:
      type: password
  jvmOptions:
    "-Xmx": "1G"
    "-Xms": "1G"
    "-XX":
      "UseG1GC": "true"
    javaSystemProperties:
      # Enable SSL for JMX
      - name: "com.sun.management.jmxremote.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.registry.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.ssl.need.client.auth"
        value: "true"
      # SSL keystore and truststore using mounted certificates
      - name: "javax.net.ssl.keyStore"
        value: "/mnt/jmx-certs/keystore.jks"
      - name: "javax.net.ssl.keyStorePassword"
        value: "${JMX_KEYSTORE_PASSWORD}"
      - name: "javax.net.ssl.trustStore"
        value: "/mnt/jmx-certs/truststore.jks"
      - name: "javax.net.ssl.trustStorePassword"
        value: "${JMX_TRUSTSTORE_PASSWORD}"

# JMX SSL Certificates
# Generate these using scripts/generate-jmx-certificates.sh
jmxCertificates:
  keystore: "/u3+7QAAAAIAAAACAAAAAgAGY2Fyb290AAABmHUuIi0ABVguNTA5AAADmTCCA5UwggJ9oAMCAQICCQCCTGZ9plD56zANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJVUzEOMAwGA1UECAwFU3RhdGUxDTALBgNVBAcMBENpdHkxFTATBgNVBAoMDE9yZ2FuaXphdGlvbjELMAkGA1UECwwCSVQxDzANBgNVBAMMBkpNWC1DQTAeFw0yNTA4MDQxMzAzMzNaFw0zNTA4MDIxMzAzMzNaMGExCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMQswCQYDVQQLDAJJVDEPMA0GA1UEAwwGSk1YLUNBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwqElG+nDut4080EfGywVlB3bkwedMd7gzXQ/XQo8sK8rGWR7BkieN8F0tVR1nY58yXxiRfhFuAz4A4I7vcgMdxDYiBVXB9I+zVESLPf0Sw7MzDp0dqovaTbz7dTHF1HUoiN/9sDyuFwuq/qD5gw1k2I5158mT4Xie0wcoKEtvAYH3qPnugWdPgf67ZChRc+u+vw08+n+WD00jf53CSdY571/Jyi8N/a2z+vYMmDvCsqRP1vXWrug5Hz5T7Nn7Knec5PQQmb9swRry71/QC4DH8uMRj1xiJr0w/dpkgyfvWyFWNXRfmmDdY1YCzplq/1ApJk8f9TWoTI3pk5GYAYIWwIDAQABo1AwTjAdBgNVHQ4EFgQU6rjZK5tQLJKYDZv0U9/Fav++21gwHwYDVR0jBBgwFoAU6rjZK5tQLJKYDZv0U9/Fav++21gwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAQBWSf5HCnBEyXLNc5vaHvvXjEKArRRGwJAVTDB1i9vhIv/TrRLCCX6hv9LvqkYAd134yNTktBoBCAd3ZogQYmD+3IW5MgddgW95rH5i6+AgvmjFHRZjPIbb+U/ynRpT1BVyWut2MEcskV9JWZUQt3eao5QH4QpUrqs1g6ZWp4E14oDVPAB+ZWzh8Qryy/da8m0EM1Yh+HyF23JHLocVWiW3P3fl16DomXpAdoBELtW34x11d85FXbZrg8Z1czFgjqZFZzYHLUzgy1PnqPv04NKiVRo+XtJTjT/VrreDvXD3LgWjWyXQLL4JK2z1/0LSUXvzG0ghyM7+10qqWTg9TxQAAAAEACWthZmthLWpteAAAAZh1LiMCAAAFAjCCBP4wDgYKKwYBBAEqAhEBAQUABIIE6qLaBach1Q70X5SiH/usODUJc4pvBNBYcEhSYoqA4wVYCcYzbmOrQ6SkvF/afHsW0lGd5+6cfOvabY5xU4FkaK6uEDu4LKtIDrIgGUNq5nNeW8GxhkyZtswglXrc+QYR+em6BZwaqpfXY0kzrXM5oy+YYE2eP27WlSvi4LBnlt5yzg3siMOWWeJsQPMbaKZhIl3eTlD0UEQ/BWRvXHX+sCluCklrBxbpI8goajxR9AInEFQ7IFiyDE6zuFT6Pv/OuKUpeGEmDkfRQkULR/acqI59V05I+EogiqzOwhhFkW/301OxvYmr8QtlGITage7ZCplMd+C575e+IIO1O7NdyE1H+/3sZ7oStTwnxJLmmCE6TAsZRQxpZUO3Si5uy/QqEyCOnO+tW+5eUgIjXAf1jT+hjTo84DKLhr14Gz6n4hO3BXt54xlAi1OeqKhgsd76PFeP4PaWyiHIXMlsBWfnapwwE5X/IOOjuWZCKQZ9iwmD/+TfcO6zaJAdfeVzQwwos/cg3kRNIikZ4T3MICI06VPCzwGWH597ZJ+3Y5fDrShpJC0F00tlnednfOvkNrEJzAxO1hhW6vKIexWi090XPkE0GitobXbY4ukO4ZBt2HU5RnC6t/fPWZFy/QFgzZmK2lxdQAsEJF3sABQDe7QlGW1RBwe+iwXxGyVDmBW0IkcbJqV6j/BoUEGZcMXC07lk/dLPI/ylmkjZV86JG9bRrZE4QgNEsF+0av6HYBFR66TE9KvvCqN37jj2sgfVjE8Ak4zgP9KPipZj4RoBHk/7WDyYIsnXiy9vRlTl5FYd9Q+nPASfQcxoKeUlL79MG10/4n7gWyaNuQdKr5jtQAMJpkK2nnDidI506QgFfyeTu80EEI/Me3BG1ry/Dr73tP2dcIc3D+FcByzMnd2dLFB2+psk9wQWGbHppmLD/ARmbh/9aKs58f/Wx7HKnsFdKQq4XekGffuJR1JGs6ZXwugCeiQofCKuOFARQCijrb+fZlX53wNzPo7GhZdDYFChUnFHncueWpoTX0TnmL49LDvuvfLstm7ITu+jsO98BV1aTCNiPV78HLVefMDkl4ifm2w8yzUY+9ZYIQWukfxfnrMjXLEBoIGFB9bZLBcfmgsl/8P/GjxtKjQQP4BTenj1KSZ0mEH1bDWrgIvihnJ4mHPWioZeLenfjKUzvrSpPv10UwZPcoM6EzK19O+YhgBzosLQmbdXBsmeJIZRuPG0eSTjT2EmrWC02o2g9xrhSRng/lSzF6CYv+WJhufCtK52mnb6nY4gFeemoTwrrk6BLfCZvOsJ/0Puan16PvOZxOm2M+Dwmt+zv0AQv6h2rjrEWqZodtN3fi5ED/hyrBXBruzPb6LzLVF3Ki+rvLoPDBomqWgyABq304teqORObRXjtQJswQMI2J4NkVzdB9Z16jNquKsC9v1ueezRt82Vj5uhdbTkaPW96DqMokzJrrapq4Lr5yIjhIMV6voNeGkYeMYuC+tXFDpXhf5Bl/ot2vQZGcUWmq4jo9o9J3Rs5SP+FRyarl9b37Zj06Yds6t1CYRkevhVzOYX5ifSIax8LAk/vqoXRfk43S/n+2l3zqSu9b7sdYKACU8ZBZP2w1Fpr7M1pKJOtDWZkf6PZ8HTUeRgFvLemp89KdDz3WeuUppwCVQ09foVlvSobAaQp00AAAACAAVYLjUwOQAAA0UwggNBMIICKQIJAJauoB6b5mjbMA0GCSqGSIb3DQEBCwUAMGExCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMQswCQYDVQQLDAJJVDEPMA0GA1UEAwwGSk1YLUNBMB4XDTI1MDgwNDEzMDMzNFoXDTM1MDgwMjEzMDMzNFowZDELMAkGA1UEBhMCVVMxDjAMBgNVBAgTBVN0YXRlMQ0wCwYDVQQHEwRDaXR5MRUwEwYDVQQKEwxPcmdhbml6YXRpb24xCzAJBgNVBAsTAklUMRIwEAYDVQQDEwlrYWZrYS1qbXgwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCT7j+/DiMmo64FxSDL8iML8t7v89WcQ6bSYAueFircP+VoDBwgN8X1zNfq3lihPjABICTi3OSf0W6EKhlPFkukWI9MqsBDyuESohTlZXcQxgLylI4K2hXLp4UK0xrz/0RFMZPVkQwnb3sE2KAwSaexg+Jxx7F/Rywfuiguf9KRZvQAXvu+COPR4YyeUYiMn7mKe29SQTmYcIqnfedrBEis0XdoRJCBKEBnm4DrqAEMv+7oLaFd7fz40asTq6q2UKbrrjcSjld7aSjAeVYmcOqf8VRmQ+yEXAePmbI0/U8dk8iiPum3z8dTfaBcKXj55GsLZSvwH2/Dnns0RqMcIJezAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAE/TKq0pM2tXec6uDuq2opckEJZG4MLiIqbRmg8g5tJKRWGUOXDsTE6EOih0yNeNvZz5tmv+KQ7zeRhDu0/7yTAJ7b2G/3uHhlMUgDupP0zGN58g4QAXYRHUlT5AKl4ughM+REDAOoBGqUpgO9ytyEoEtLRHGFY6FTWYRXkCAJ6mdW5ADTWtHUU4NYj9chgy+lgJqBqFBejv1OYSGaeqmbi5/wFjlFmL3wlNZMDix4V+X1ymIjrt9C/ZBBHbwbG3ZZEZi0bex8fDzn8DUaZ5ySx8A94zgj+An8fI2apEIMPuHahU+YKwm6KdoV/XeeBAwS+1GE1xqOHnRqtP9pwVD0sABVguNTA5AAADmTCCA5UwggJ9oAMCAQICCQCCTGZ9plD56zANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJVUzEOMAwGA1UECAwFU3RhdGUxDTALBgNVBAcMBENpdHkxFTATBgNVBAoMDE9yZ2FuaXphdGlvbjELMAkGA1UECwwCSVQxDzANBgNVBAMMBkpNWC1DQTAeFw0yNTA4MDQxMzAzMzNaFw0zNTA4MDIxMzAzMzNaMGExCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMQswCQYDVQQLDAJJVDEPMA0GA1UEAwwGSk1YLUNBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwqElG+nDut4080EfGywVlB3bkwedMd7gzXQ/XQo8sK8rGWR7BkieN8F0tVR1nY58yXxiRfhFuAz4A4I7vcgMdxDYiBVXB9I+zVESLPf0Sw7MzDp0dqovaTbz7dTHF1HUoiN/9sDyuFwuq/qD5gw1k2I5158mT4Xie0wcoKEtvAYH3qPnugWdPgf67ZChRc+u+vw08+n+WD00jf53CSdY571/Jyi8N/a2z+vYMmDvCsqRP1vXWrug5Hz5T7Nn7Knec5PQQmb9swRry71/QC4DH8uMRj1xiJr0w/dpkgyfvWyFWNXRfmmDdY1YCzplq/1ApJk8f9TWoTI3pk5GYAYIWwIDAQABo1AwTjAdBgNVHQ4EFgQU6rjZK5tQLJKYDZv0U9/Fav++21gwHwYDVR0jBBgwFoAU6rjZK5tQLJKYDZv0U9/Fav++21gwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAQBWSf5HCnBEyXLNc5vaHvvXjEKArRRGwJAVTDB1i9vhIv/TrRLCCX6hv9LvqkYAd134yNTktBoBCAd3ZogQYmD+3IW5MgddgW95rH5i6+AgvmjFHRZjPIbb+U/ynRpT1BVyWut2MEcskV9JWZUQt3eao5QH4QpUrqs1g6ZWp4E14oDVPAB+ZWzh8Qryy/da8m0EM1Yh+HyF23JHLocVWiW3P3fl16DomXpAdoBELtW34x11d85FXbZrg8Z1czFgjqZFZzYHLUzgy1PnqPv04NKiVRo+XtJTjT/VrreDvXD3LgWjWyXQLL4JK2z1/0LSUXvzG0ghyM7+10qqWTg9TxbkLTllPa/NVhcM57OQrtqKgK14H"
  truststore: "/u3+7QAAAAIAAAABAAAAAgAGY2Fyb290AAABmHUuI6UABVguNTA5AAADmTCCA5UwggJ9oAMCAQICCQCCTGZ9plD56zANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJVUzEOMAwGA1UECAwFU3RhdGUxDTALBgNVBAcMBENpdHkxFTATBgNVBAoMDE9yZ2FuaXphdGlvbjELMAkGA1UECwwCSVQxDzANBgNVBAMMBkpNWC1DQTAeFw0yNTA4MDQxMzAzMzNaFw0zNTA4MDIxMzAzMzNaMGExCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMQswCQYDVQQLDAJJVDEPMA0GA1UEAwwGSk1YLUNBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwqElG+nDut4080EfGywVlB3bkwedMd7gzXQ/XQo8sK8rGWR7BkieN8F0tVR1nY58yXxiRfhFuAz4A4I7vcgMdxDYiBVXB9I+zVESLPf0Sw7MzDp0dqovaTbz7dTHF1HUoiN/9sDyuFwuq/qD5gw1k2I5158mT4Xie0wcoKEtvAYH3qPnugWdPgf67ZChRc+u+vw08+n+WD00jf53CSdY571/Jyi8N/a2z+vYMmDvCsqRP1vXWrug5Hz5T7Nn7Knec5PQQmb9swRry71/QC4DH8uMRj1xiJr0w/dpkgyfvWyFWNXRfmmDdY1YCzplq/1ApJk8f9TWoTI3pk5GYAYIWwIDAQABo1AwTjAdBgNVHQ4EFgQU6rjZK5tQLJKYDZv0U9/Fav++21gwHwYDVR0jBBgwFoAU6rjZK5tQLJKYDZv0U9/Fav++21gwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAQBWSf5HCnBEyXLNc5vaHvvXjEKArRRGwJAVTDB1i9vhIv/TrRLCCX6hv9LvqkYAd134yNTktBoBCAd3ZogQYmD+3IW5MgddgW95rH5i6+AgvmjFHRZjPIbb+U/ynRpT1BVyWut2MEcskV9JWZUQt3eao5QH4QpUrqs1g6ZWp4E14oDVPAB+ZWzh8Qryy/da8m0EM1Yh+HyF23JHLocVWiW3P3fl16DomXpAdoBELtW34x11d85FXbZrg8Z1czFgjqZFZzYHLUzgy1PnqPv04NKiVRo+XtJTjT/VrreDvXD3LgWjWyXQLL4JK2z1/0LSUXvzG0ghyM7+10qqWTg9TxR/yycUDRycC9yVg/Ym0bCQbCThR"

jmxPasswords:
  keystorePassword: "M12uCbIvQbKQWgv9y8DcCA=="
  truststorePassword: "kXQO9ihqiSTqAs8hHshilw=="
  # JMX authentication passwords
  monitorPassword: ""
  controlPassword: ""
