entityOperator:
  topicOperator: {}
  userOperator: {}
kafka:
  config:
    auto.create.topics.enable: false
    log.message.format.version: "2.8"
    offsets.topic.replication.factor: 3
    transaction.state.log.min.isr: 2
    transaction.state.log.replication.factor: 3
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    # plain: {}
    # tls: {}
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
  version: 3.9.0
  # JMX DISABLED - Security vulnerability mitigation
  # Removing jmxOptions completely disables JMX port 9999
  # jmxOptions:
  #   authentication:
  #     type: password
  jvmOptions:
    "-Xmx": "2G"
    "-Xms": "2G"
    "-XX":
      "UseG1GC": "true"
      "MaxGCPauseMillis": "20"
  # Metrics configuration for Prometheus JMX Exporter
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: kafka-metrics
        key: kafka-metrics-config.yml
strimzi-kafka-operator:
  watchAnyNamespace: true
zookeeper:
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
  # JMX DISABLED - Security vulnerability mitigation
  # Removing jmxOptions completely disables JMX port 9999
  # jmxOptions:
  #   authentication:
  #     type: password
  jvmOptions:
    "-Xmx": "1G"
    "-Xms": "1G"
    "-XX":
      "UseG1GC": "true"

# JMX SSL Certificates
# Generate these using scripts/generate-jmx-certificates.sh
jmxCertificates:
  # Base64 encoded keystore file
  keystore: ""
  # Base64 encoded truststore file  
  truststore: ""

# JMX DISABLED - All JMX configurations removed for security
# Port 9999 is no longer exposed, eliminating the vulnerability
# 
# Note: JMX-based monitoring is disabled. Use Prometheus metrics instead:
# - Kafka metrics available on port 9404
# - Prometheus JMX Exporter provides comprehensive metrics
# - No unencrypted JMX traffic

# Legacy JMX configurations (DISABLED)
# jmxSecurity:
#   enabled: false
# jmxPasswords:
#   keystorePassword: ""
#   truststorePassword: ""
