entityOperator:
  topicOperator: {}
  userOperator: {}
kafka:
  config:
    auto.create.topics.enable: false
    log.message.format.version: "2.8"
    offsets.topic.replication.factor: 3
    transaction.state.log.min.isr: 2
    transaction.state.log.replication.factor: 3
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    # plain: {}
    # tls: {}
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
  version: 3.9.0
  # JMX configuration - using password auth with Strimzi
  jmxOptions:
    authentication:
      type: password
  jvmOptions:
    "-Xmx": "2G"
    "-Xms": "2G"
    "-XX":
      "UseG1GC": "true"
      "MaxGCPauseMillis": "20"
    javaSystemProperties:
      # JMX-specific SSL configuration
      - name: "com.sun.management.jmxremote.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.registry.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.ssl.need.client.auth"
        value: "true"
      # JMX-specific SSL config files
      - name: "com.sun.management.jmxremote.ssl.config.file"
        value: "/opt/kafka/jmx-ssl.properties"
  # Metrics configuration for Prometheus JMX Exporter
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: kafka-metrics
        key: kafka-metrics-config.yml
strimzi-kafka-operator:
  watchAnyNamespace: true
zookeeper:
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
  # JMX configuration - using password auth with Strimzi
  jmxOptions:
    authentication:
      type: password
  jvmOptions:
    "-Xmx": "1G"
    "-Xms": "1G"
    "-XX":
      "UseG1GC": "true"
    javaSystemProperties:
      # JMX-specific SSL configuration
      - name: "com.sun.management.jmxremote.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.registry.ssl"
        value: "true"
      - name: "com.sun.management.jmxremote.ssl.need.client.auth"
        value: "true"
      # JMX-specific SSL config files
      - name: "com.sun.management.jmxremote.ssl.config.file"
        value: "/opt/kafka/jmx-ssl.properties"

# JMX SSL Certificates
# Generate these using scripts/generate-jmx-certificates.sh
jmxCertificates:
  keystorePath: "certs/keystore.jks"
  truststorePath: "certs/truststore.jks"

jmxPasswords:
  keystorePasswordPath: "certs/keystore.password"
  truststorePasswordPath: "certs/truststore.password"
  # JMX authentication passwords
  monitorPasswordPath: "certs/monitor.password"
  controlPasswordPath: "certs/control.password"
