entityOperator:
  topicOperator: {}
  userOperator: {}
kafka:
  config:
    auto.create.topics.enable: false
    log.message.format.version: "2.8"
    offsets.topic.replication.factor: 3
    transaction.state.log.min.isr: 2
    transaction.state.log.replication.factor: 3
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    # plain: {}
    # tls: {}
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
  version: 3.9.0
  # JMX DISABLED - Security vulnerability mitigation
  # Removing jmxOptions completely disables JMX port 9999
  # jmxOptions:
  #   authentication:
  #     type: password
  jvmOptions:
    "-Xmx": "2G"
    "-Xms": "2G"
    "-XX":
      "UseG1GC": "true"
      "MaxGCPauseMillis": "20"
  # Metrics configuration for Prometheus JMX Exporter
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: kafka-metrics
        key: kafka-metrics-config.yml
  # Template configuration to completely disable JMX
  template:
    kafkaContainer:
      env:
        # Override Strimzi's default JMX settings to completely disable JMX
        - name: KAFKA_JMX_OPTS
          value: "-Dcom.sun.management.jmxremote=false"
strimzi-kafka-operator:
  watchAnyNamespace: true
zookeeper:
  replicas: 3
  storage:
    deleteClaim: false
    size: 10Gi
    type: persistent-claim
  # JMX DISABLED - Security vulnerability mitigation
  # Removing jmxOptions completely disables JMX port 9999
  # jmxOptions:
  #   authentication:
  #     type: password
  jvmOptions:
    "-Xmx": "1G"
    "-Xms": "1G"
    "-XX":
      "UseG1GC": "true"
  # Template configuration to completely disable JMX
  template:
    zookeeperContainer:
      env:
        # Override Strimzi's default JMX settings to completely disable JMX
        - name: KAFKA_JMX_OPTS
          value: "-Dcom.sun.management.jmxremote=false"

# JMX SSL Certificates
# Generate these using scripts/generate-jmx-certificates.sh
jmxCertificates:
  # Base64 encoded keystore file
  keystore: ""
  # Base64 encoded truststore file  
  truststore: ""

# JMX COMPLETELY DISABLED - Security vulnerability mitigation
# 
# Problem: Strimzi adds default JMX options (-Dcom.sun.management.jmxremote=true) 
# before custom javaSystemProperties, making it impossible to disable JMX using 
# only javaSystemProperties.
#
# Solution: Use KAFKA_JMX_OPTS environment variable through template configuration.
# This overrides Strimzi's default JMX settings and completely disables the JMX agent.
#
# Security benefits:
# - Port 9999 is not exposed
# - JMX agent is completely disabled
# - No remote JMX access possible
# - Eliminates JMX-related vulnerabilities
#
# Monitoring: Use Prometheus metrics instead
# - Kafka metrics available on port 9404
# - Prometheus JMX Exporter provides comprehensive metrics
# - Secure and Kubernetes-native monitoring solution

# Legacy JMX configurations (DISABLED)
# jmxSecurity:
#   enabled: false
# jmxPasswords:
#   keystorePassword: ""
#   truststorePassword: ""
